// ========== 申请清单页：真实 query_policy 返回记录（2026-09-13 实调） ==========
// 来源：AI 对话实际调用 policy-search MCP query_policy 的完整返回（users 提供截图/JSON）。
// 用途：mock → 真实数据过渡。真实返回已带 board/input_kind/requires_evidence/match。
// 说明：接入"对话工具消息 → 前端渲染"动态链路后，此文件仅作 fallback 样例，不再作主数据源。
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const realQueryPolicyResult: any = {
  total_policies: 1,
  results: [
    {
      policy_title: '重庆邮电大学普通本科学生奖助学金评审办法',
      policy_category: 'scholarship',
      overall_verdict: 'needs_more_info',
      veto_blocked: false,
      triggered_vetoes: [],
      board_matches: {
        veto: [
          { id: 'condition_005', item: '课程修读与学业表现', match: 'clear' },
          { id: 'condition_026', item: '遵纪守法与校规遵守', match: 'clear' },
          { id: 'condition_038', item: '纪律处分记录', match: 'clear' },
          { id: 'condition_041', item: '纪律处分限制', match: 'clear' },
          { id: 'condition_039', item: '申请诚信要求', match: 'clear' },
        ],
        base: [
          { id: 'condition_009', item: '年级要求', match: 'missing_info' },
          { id: 'condition_028', item: '学习态度与进取精神', match: 'needs_manual_review' },
          { id: 'condition_032', item: '学业表现要求', match: 'needs_manual_review' },
          { id: 'condition_034', item: '申请时限', match: 'needs_manual_review' },
          { id: 'condition_036', item: '公示要求', match: 'needs_manual_review' },
          { id: 'condition_037', item: '申请时效性', match: 'needs_manual_review' },
        ],
        bonus: [
          { id: 'condition_011', item: '学业成绩排名', match: 'met' },
          { id: 'condition_013', item: '学业成绩排名', match: 'met' },
          { id: 'condition_016', item: '学业成绩排名', match: 'met' },
          { id: 'condition_018', item: '学业成绩排名', match: 'met' },
          { id: 'condition_020', item: '学业成绩排名', match: 'met' },
          { id: 'condition_012', item: '综合素质测评成绩排名', match: 'met' },
          { id: 'condition_014', item: '综合素质测评成绩排名', match: 'met' },
          { id: 'condition_017', item: '综合素质测评成绩排名', match: 'met' },
          { id: 'condition_019', item: '综合素质测评成绩排名', match: 'met' },
          { id: 'condition_021', item: '综合素质测评成绩排名', match: 'met' },
          { id: 'condition_022', item: '学科竞赛获奖', match: 'needs_manual_review' },
          { id: 'condition_023', item: '文体艺术类竞赛获奖', match: 'needs_manual_review' },
          { id: 'condition_010', item: '义工服务时长', match: 'missing_info' },
          { id: 'condition_042', item: '义工活动时长认定', match: 'needs_manual_review' },
          { id: 'condition_043', item: '学生干部履职折算义工时长', match: 'needs_manual_review' },
          { id: 'condition_008', item: '助学金兼得政策', match: 'needs_manual_review' },
        ],
        other: [
          { id: 'condition_002', item: '政治方向与思想立场', match: 'informational' },
          { id: 'condition_003', item: '遵纪守法情况', match: 'informational' },
          { id: 'condition_004', item: '道德品质与行为习惯', match: 'informational' },
          { id: 'condition_015', item: '家庭经济困难认定', match: 'informational' },
          { id: 'condition_025', item: '思想政治表现', match: 'informational' },
          { id: 'condition_027', item: '道德品质要求', match: 'informational' },
          { id: 'condition_030', item: '品行要求', match: 'informational' },
          { id: 'condition_031', item: '品行要求', match: 'informational' },
          { id: 'condition_006', item: '评定方式区分', match: 'informational' },
          { id: 'condition_007', item: '申请类别限制', match: 'informational' },
          { id: 'condition_035', item: '学院评审组织', match: 'informational' },
          { id: 'condition_001', item: '学生身份要求', match: 'informational' },
          { id: 'condition_024', item: '其他符合创新活动实施方案的项目', match: 'informational' },
          { id: 'condition_029', item: '家庭经济困难及生活作风要求', match: 'informational' },
          { id: 'condition_033', item: '家庭经济困难认定', match: 'informational' },
          { id: 'condition_040', item: '学生工作部认定资格否决', match: 'informational' },
        ],
      },
      category_matches: {
        gpa: { label: '绩点/成绩要求', ids: ['condition_011', 'condition_013', 'condition_016', 'condition_018', 'condition_020'] },
        academic: { label: '学业表现要求', ids: ['condition_005', 'condition_009', 'condition_012', 'condition_014', 'condition_017', 'condition_019', 'condition_021', 'condition_028', 'condition_032'] },
        disciplinary: { label: '纪律/品行要求', ids: ['condition_002', 'condition_003', 'condition_004', 'condition_015', 'condition_025', 'condition_026', 'condition_027', 'condition_030', 'condition_031', 'condition_038', 'condition_041'] },
        competition: { label: '竞赛/获奖要求', ids: ['condition_022', 'condition_023'] },
        bonus: { label: '加分项', ids: ['condition_010', 'condition_042', 'condition_043'] },
        procedural: { label: '流程性要求', ids: ['condition_006', 'condition_007', 'condition_008', 'condition_034', 'condition_035', 'condition_036', 'condition_037', 'condition_039'] },
        other: { label: '其他要求', ids: ['condition_001', 'condition_024', 'condition_029', 'condition_033', 'condition_040'] },
      },
      condition_matches: [
        { item: '学业成绩排名', requirement: '专业（或年级）前10%', source_quote: '学业成绩和综合素质测评成绩排名均应在专业（或年级）前10%。', id: 'condition_011', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前10%要求' },
        { item: '学业成绩排名', requirement: '排名前10%', source_quote: '学业成绩和综合素质测评成绩排名均应在专业（或年级）前10%。', id: 'condition_013', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前10%要求' },
        { item: '学业成绩排名', requirement: '学业成绩排名在专业（或年级）前1/3', source_quote: '学业成绩……排名均应在专业（或年级）前1/3', id: 'condition_016', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前33.33%要求' },
        { item: '学业成绩排名', requirement: '排名前15%', source_quote: '学业成绩和综合素质测评成绩排名均应在专业（或年级）前15%。', id: 'condition_018', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前15%要求' },
        { item: '学业成绩排名', requirement: '排名在专业（或年级）前40%', source_quote: '学业成绩和综合素质测评成绩排名均应在专业（或年级）前40%。', id: 'condition_020', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前40%要求' },
        { item: '课程修读与学业表现', requirement: '所修课程无补考、重修', source_quote: '（四）学习目的明确，学习态度端正，评定学年所修课程（不含任选、再修、重修、第二专业课程）无补考、重修。', id: 'condition_005', board: 'veto', input_kind: 'yes_no', requires_evidence: false, match: 'clear', user_value: '未触发', detail: '未触发否决项' },
        { item: '年级要求', requirement: '在校二年级以上', source_quote: '在校二年级以上优秀学生；', id: 'condition_009', board: 'base', input_kind: 'yes_no', requires_evidence: false, match: 'missing_info', user_value: '未提供', detail: '缺少 none 信息' },
        { item: '综合素质测评成绩排名', requirement: '专业（或年级）前10%', source_quote: '学业成绩和综合素质测评成绩排名均应在专业（或年级）前10%。', id: 'condition_012', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前10%要求' },
        { item: '综合素质测评成绩排名', requirement: '排名前10%', source_quote: '学业成绩和综合素质测评成绩排名均应在专业（或年级）前10%。', id: 'condition_014', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前10%要求' },
        { item: '综合素质测评成绩排名', requirement: '综合素质测评成绩排名在专业（或年级）前1/3', source_quote: '综合素质测评成绩排名均应在专业（或年级）前1/3', id: 'condition_017', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前33.33%要求' },
        { item: '综合素质测评成绩排名', requirement: '排名前15%', source_quote: '学业成绩和综合素质测评成绩排名均应在专业（或年级）前15%。', id: 'condition_019', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前15%要求' },
        { item: '综合素质测评成绩排名', requirement: '排名在专业（或年级）前40%', source_quote: '学业成绩和综合素质测评成绩排名均应在专业（或年级）前40%。', id: 'condition_021', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'met', user_value: '前10.0%', detail: '满足前40%要求' },
        { item: '学习态度与进取精神', requirement: '勤奋学习，积极上进', source_quote: '4. 勤奋学习，积极上进；', id: 'condition_028', board: 'base', input_kind: 'yes_no', requires_evidence: false, match: 'needs_manual_review', detail: '定性条件需人工审核' },
        { item: '学业表现要求', requirement: '学业表现良好', source_quote: '符合申请条件的家庭经济困难学生，按照特别困难、困难、一般困难顺序，结合学业、品行等现实表现', id: 'condition_032', board: 'base', input_kind: 'yes_no', requires_evidence: false, match: 'needs_manual_review', detail: '定性条件需人工审核' },
        { item: '政治方向与思想立场', requirement: '具有坚定正确的政治方向和远大理想，热爱社会主义祖国，拥护中国共产党的领导', source_quote: '（一）具有坚定正确的政治方向和远大理想，热爱社会主义祖国，拥护中国共产党的领导；', id: 'condition_002', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '遵纪守法情况', requirement: '自觉遵守宪法、法律法规，遵守校规校纪', source_quote: '（二）自觉遵守宪法、法律法规，遵守校规校纪；', id: 'condition_003', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '道德品质与行为习惯', requirement: '具备良好的道德品质和行为习惯：热爱生活、关心集体，尊敬师长、团结同学，诚实守信、乐于助人，生活俭朴、身心健康，积极参加公益活动', source_quote: '（三）具备良好的道德品质和行为习惯：热爱生活、关心集体，尊敬师长、团结同学，诚实守信、乐于助人，生活俭朴、身心健康，积极参加公益活动；', id: 'condition_004', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '家庭经济困难认定', requirement: '已被认定为家庭经济困难学生', source_quote: '被认定为家庭经济困难学生', id: 'condition_015', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '思想政治表现', requirement: '热爱社会主义祖国，拥护中国共产党的领导', source_quote: '热爱社会主义祖国，拥护中国共产党的领导；', id: 'condition_025', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '遵纪守法与校规遵守', requirement: '无违法违纪记录，无违反校纪校规行为', source_quote: '遵守宪法和法律，遵守学校规章制度；', id: 'condition_026', board: 'veto', input_kind: 'yes_no', requires_evidence: false, match: 'clear', user_value: '未触发', detail: '未触发否决项' },
        { item: '道德品质要求', requirement: '诚实守信，道德品质优良', source_quote: '3. 诚实守信，道德品质优良；', id: 'condition_027', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '品行要求', requirement: '自立自强，乐于助人，积极参加公益活动', source_quote: '6. 自立自强，乐于助人，积极参加公益活动。', id: 'condition_030', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '品行要求', requirement: '品行优良', source_quote: '符合申请条件的家庭经济困难学生，按照特别困难、困难、一般困难顺序，结合学业、品行等现实表现', id: 'condition_031', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '纪律处分记录', requirement: '无通报批评或纪律处分记录', source_quote: '（二）违反校规校纪，并受到院、校通报批评或学校纪律处分者；', id: 'condition_038', board: 'veto', input_kind: 'yes_no', requires_evidence: false, match: 'clear', user_value: '未触发', detail: '未触发否决项' },
        { item: '纪律处分限制', requirement: '未受警告及以上处分', source_quote: '在受益期间违反国家法律法规及学校规章制度，受到学校警告以上处分者，从受到处分次月起终止奖助学金发放。', id: 'condition_041', board: 'veto', input_kind: 'yes_no', requires_evidence: false, match: 'clear', user_value: '未触发', detail: '未触发否决项' },
        { item: '学科竞赛获奖', requirement: '获得省部级以上等级奖', source_quote: '在课外科技创新、学科竞赛活动中获得省部级以上等级奖；', id: 'condition_022', board: 'bonus', input_kind: 'select', requires_evidence: false, match: 'needs_manual_review', detail: '定性条件需人工审核' },
        { item: '文体艺术类竞赛获奖', requirement: '获得省部级以上等级奖', source_quote: '在文体艺术等竞赛活动中获得省部级以上等级奖；', id: 'condition_023', board: 'bonus', input_kind: 'select', requires_evidence: false, match: 'needs_manual_review', detail: '定性条件需人工审核' },
        { item: '义工服务时长', requirement: '义工活动时间 ≥ 20小时', source_quote: '评定学年内从事义工活动时间原则上不低于20小时；', id: 'condition_010', board: 'bonus', input_kind: 'number', requires_evidence: true, match: 'missing_info', user_value: '未提供', detail: '缺少 小时 信息' },
        { item: '义工活动时长认定', requirement: '可参照注册志愿者的志愿服务时长', source_quote: '从事义工活动时长认定，可参照注册志愿者的志愿服务时长。', id: 'condition_042', board: 'bonus', input_kind: 'select', requires_evidence: false, match: 'needs_manual_review', detail: '加分项需人工核实' },
        { item: '学生干部履职折算义工时长', requirement: "担任各级各类学生干部、干事等，经主管部门或学院考核为'合格'以上", source_quote: '评定学年内担任各级各类学生干部、干事等，经主管部门或学院考核为"合格"以上，也可折算为一定义工时长。', id: 'condition_043', board: 'bonus', input_kind: 'select', requires_evidence: false, match: 'needs_manual_review', detail: '加分项需人工核实' },
        { item: '评定方式区分', requirement: '国家奖学金、春华秋实奖学金及奖励金额≥8000元的社会奖学金须公开申报、评审或答辩；其余奖学金按综合素质测评成绩排序评定', source_quote: '（二）国家奖学金、春华秋实奖学金及奖励金额为8000元以上的社会奖学金采用公开申报、评审或答辩方式评定，其他奖学金按评定学年综合素质测评成绩从高到低排序评定；', id: 'condition_006', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '申请类别限制', requirement: '学生在同一学年只能申请获得一类奖学金（科创文体奖学金除外）', source_quote: '（三）学生在同一学年只能申请获得一类奖学金（科创文体奖学金除外）。', id: 'condition_007', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '助学金兼得政策', requirement: '家庭经济困难学生可同时申请获得助学金', source_quote: '家庭经济困难学生可同时申请获得助学金。', id: 'condition_008', board: 'bonus', input_kind: 'select', requires_evidence: false, match: 'needs_manual_review', detail: '优先条件需人工评估' },
        { item: '申请时限', requirement: '在规定时间内提交申请', source_quote: '学生根据各类奖助学金申请条件，在规定时间内提出申请', id: 'condition_034', board: 'base', input_kind: 'upload', requires_evidence: true, match: 'needs_manual_review', detail: '流程性要求需用户自行确认' },
        { item: '学院评审组织', requirement: '学院成立评审小组进行评审', source_quote: '学院成立学生奖助学金评审小组，对申请学生进行评审', id: 'condition_035', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '公示要求', requirement: '公示期不少于3天，且无异议', source_quote: '公示3天无异议后报送学生工作部（处）审查', id: 'condition_036', board: 'base', input_kind: 'number', requires_evidence: true, match: 'needs_manual_review', detail: '流程性要求需用户自行确认' },
        { item: '申请时效性', requirement: '必须在规定时间内完成申请与材料提交', source_quote: '（一）未在规定时间内提出申请或提交材料者；', id: 'condition_037', board: 'base', input_kind: 'upload', requires_evidence: true, match: 'needs_manual_review', detail: '流程性要求需用户自行确认' },
        { item: '申请诚信要求', requirement: '申请及评审过程须真实诚信', source_quote: '（三）在奖助学金申请和评审推荐过程中弄虚作假者；', id: 'condition_039', board: 'veto', input_kind: 'yes_no', requires_evidence: false, match: 'clear', user_value: '未触发', detail: '未触发否决项' },
        { item: '学生身份要求', requirement: '在籍全日制本科学生', source_quote: '第二条 本办法适用于我校在籍全日制本科学生。', id: 'condition_001', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '其他符合创新活动实施方案的项目', requirement: '须经认定符合校级创新活动实施方案要求', source_quote: '其他符合《重庆邮电大学学生科技文化创新活动工作实施方案》相关条件的项目。', id: 'condition_024', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '家庭经济困难及生活作风要求', requirement: '家庭经济困难，生活俭朴', source_quote: '5. 家庭经济困难，生活俭朴；', id: 'condition_029', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '家庭经济困难认定', requirement: '已被认定为家庭经济困难学生（特别困难/困难/一般困难）', source_quote: '符合申请条件的家庭经济困难学生，按照特别困难、困难、一般困难顺序', id: 'condition_033', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
        { item: '学生工作部认定资格否决', requirement: '未被学生工作部（处）认定为不具备参评资格', source_quote: '（四）其他经学生工作部（处）认定不能参加评定者。', id: 'condition_040', board: 'other', input_kind: 'none', requires_evidence: false, match: 'informational', user_value: '—', detail: '不可量化条款，仅供知悉' },
      ],
      missing_info: ['年级要求', '义工服务时长'],
      needs_manual_review: ['学习态度与进取精神', '学业表现要求', '学科竞赛获奖', '文体艺术类竞赛获奖', '义工活动时长认定', '学生干部履职折算义工时长', '助学金兼得政策', '申请时限', '公示要求', '申请时效性'],
    },
  ],
};
