import type { Course, ProgramPlan, StudentProgress } from './types';

/** 软件工程专业课程列表（按学期排列，带先修关系） */
export const mockCourses: Course[] = [
  // 大一上
  {
    id: 'c001',
    name: '高等数学Ⅰ',
    credits: 5,
    category: 'general',
    categoryLabel: '公共基础课',
    semester: 1,
    prerequisites: [],
  },
  {
    id: 'c002',
    name: '程序设计基础',
    credits: 4,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 1,
    prerequisites: [],
  },
  {
    id: 'c003',
    name: '大学英语Ⅰ',
    credits: 3,
    category: 'general',
    categoryLabel: '公共基础课',
    semester: 1,
    prerequisites: [],
  },
  {
    id: 'c004',
    name: '线性代数',
    credits: 3,
    category: 'general',
    categoryLabel: '公共基础课',
    semester: 1,
    prerequisites: [],
  },
  // 大一下
  {
    id: 'c005',
    name: '高等数学Ⅱ',
    credits: 5,
    category: 'general',
    categoryLabel: '公共基础课',
    semester: 2,
    prerequisites: ['c001'],
  },
  {
    id: 'c006',
    name: '离散数学',
    credits: 4,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 2,
    prerequisites: ['c004'],
  },
  {
    id: 'c007',
    name: '面向对象程序设计',
    credits: 4,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 2,
    prerequisites: ['c002'],
  },
  {
    id: 'c008',
    name: '大学物理',
    credits: 4,
    category: 'general',
    categoryLabel: '公共基础课',
    semester: 2,
    prerequisites: ['c001'],
  },
  // 大二上
  {
    id: 'c009',
    name: '数据结构',
    credits: 4,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 3,
    prerequisites: ['c002', 'c006'],
  },
  {
    id: 'c010',
    name: '计算机组成原理',
    credits: 4,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 3,
    prerequisites: ['c004'],
  },
  {
    id: 'c011',
    name: '概率论与数理统计',
    credits: 3,
    category: 'general',
    categoryLabel: '公共基础课',
    semester: 3,
    prerequisites: ['c005'],
  },
  {
    id: 'c012',
    name: '大学英语Ⅱ',
    credits: 3,
    category: 'general',
    categoryLabel: '公共基础课',
    semester: 3,
    prerequisites: ['c003'],
  },
  // 大二下
  {
    id: 'c013',
    name: '算法设计与分析',
    credits: 4,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 4,
    prerequisites: ['c009'],
  },
  {
    id: 'c014',
    name: '操作系统',
    credits: 4,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 4,
    prerequisites: ['c009', 'c010'],
  },
  {
    id: 'c015',
    name: '数据库系统',
    credits: 4,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 4,
    prerequisites: ['c009'],
  },
  {
    id: 'c016',
    name: '计算机网络',
    credits: 3,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 4,
    prerequisites: ['c010'],
  },
  // 大三上
  {
    id: 'c017',
    name: '软件工程',
    credits: 3,
    category: 'core',
    categoryLabel: '专业核心课',
    semester: 5,
    prerequisites: ['c013', 'c015'],
  },
  {
    id: 'c018',
    name: '编译原理',
    credits: 3,
    category: 'elective',
    categoryLabel: '专业选修课',
    semester: 5,
    prerequisites: ['c013', 'c014'],
  },
  {
    id: 'c019',
    name: '人工智能导论',
    credits: 3,
    category: 'elective',
    categoryLabel: '专业选修课',
    semester: 5,
    prerequisites: ['c011', 'c013'],
  },
  {
    id: 'c020',
    name: '软件测试',
    credits: 2,
    category: 'elective',
    categoryLabel: '专业选修课',
    semester: 5,
    prerequisites: ['c017'],
  },
  // 大三下
  {
    id: 'c021',
    name: '软件体系结构',
    credits: 3,
    category: 'elective',
    categoryLabel: '专业选修课',
    semester: 6,
    prerequisites: ['c017'],
  },
  {
    id: 'c022',
    name: '机器学习',
    credits: 3,
    category: 'elective',
    categoryLabel: '专业选修课',
    semester: 6,
    prerequisites: ['c019'],
  },
  {
    id: 'c023',
    name: '分布式系统',
    credits: 3,
    category: 'elective',
    categoryLabel: '专业选修课',
    semester: 6,
    prerequisites: ['c014', 'c016'],
  },
  {
    id: 'c024',
    name: '移动应用开发',
    credits: 2,
    category: 'elective',
    categoryLabel: '专业选修课',
    semester: 6,
    prerequisites: ['c007'],
  },
  // 大四
  {
    id: 'c025',
    name: '毕业设计',
    credits: 8,
    category: 'practice',
    categoryLabel: '实践环节',
    semester: 7,
    prerequisites: ['c017'],
  },
  {
    id: 'c026',
    name: '专业实习',
    credits: 4,
    category: 'practice',
    categoryLabel: '实践环节',
    semester: 8,
    prerequisites: ['c017'],
  },
];

/** 当前使用的培养方案 */
export const mockCurrentPlan: ProgramPlan = {
  id: 'plan-2024-se',
  name: '2024级软件工程本科培养方案',
  major: '软件工程',
  grade: '2024级',
  version: '2024版',
  totalCredits: 160,
  courses: mockCourses,
  createdAt: '2026-09-01T10:00:00.000Z',
  confirmedAt: '2026-09-05T14:30:00.000Z',
  isCurrent: true,
};

/** 历史培养方案 */
export const mockHistoryPlans: ProgramPlan[] = [
  mockCurrentPlan,
  {
    id: 'plan-2023-se',
    name: '2023级软件工程本科培养方案',
    major: '软件工程',
    grade: '2023级',
    version: '2023版',
    totalCredits: 158,
    courses: mockCourses.slice(0, 24),
    createdAt: '2025-08-10T09:00:00.000Z',
    confirmedAt: '2025-08-12T11:00:00.000Z',
    isCurrent: false,
  },
];

/** 学生学业进度（已通过/未通过/未修读） */
export const mockStudentProgress: StudentProgress = {
  planId: 'plan-2024-se',
  courseStatuses: {
    // 大一上 - 全部通过
    c001: 'passed',
    c002: 'passed',
    c003: 'passed',
    c004: 'passed',
    // 大一下 - 全部通过
    c005: 'passed',
    c006: 'passed',
    c007: 'passed',
    c008: 'passed',
    // 大二上 - 数据结构未通过，其余通过
    c009: 'failed',
    c010: 'passed',
    c011: 'passed',
    c012: 'passed',
    // 大二下 - 全部未修读
    c013: 'not_taken',
    c014: 'not_taken',
    c015: 'not_taken',
    c016: 'not_taken',
    // 大三 - 全部未修读
    c017: 'not_taken',
    c018: 'not_taken',
    c019: 'not_taken',
    c020: 'not_taken',
    c021: 'not_taken',
    c022: 'not_taken',
    c023: 'not_taken',
    c024: 'not_taken',
    // 大四 - 全部未修读
    c025: 'not_taken',
    c026: 'not_taken',
  },
  lastSyncedAt: '2026-09-10T16:00:00.000Z',
};
